name: EPM-basic-check

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ./configure
    - run: make
    - run: make test
    - run: make distclean

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: ./configure
    - run: make
    - run: make test
    - run: make distclean
